apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  labels:
    app: my-kafka-demo
data:
  config.yaml: |
    enableUserWorkload: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-monitoring-binding
  labels:
    app: my-kafka-demo
subjects:
- kind: ServiceAccount
  name: grafana-serviceaccount
  namespace: my-kafka
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
